### ISSUE TITLE
Resubmit

### ISSUE THREAD

**Issue by Croyfet** [Juxxt/Exercise_B4Programing#1]
## ToDo
- [ ] 大問ごとにRepository分け
- [ ] GitHubでRepositoryを開いたときにMarkdownがプレビューできるのはファイル名が`readme.md`の時だけなのでRepositoryごとに一番上の階層にひとつreadme (ほかのmdに分割するのは良い)
- [ ] `.h`と`.c`の正しいフォルダわけのやり方は [CSimpleSample / LabFurukawa](https://github.com/LabFurukawa/CSimpleSample) を参考に
- [ ] 他の人が既にやってくるがreadmeにソースコード全部は載せない c.f. [Submit Style](https://github.com/Kouji-Tanaka/B4_Programming1/issues/1)
- [ ] 関数の別ファイルでの定義方法が違う
- [ ] makefileも忘れずに
